const fs = require("fs")
const path = require("path")

// Convert both Amiri and Cairo fonts
const fonts = [
  { name: "amiriRegular", file: "Amiri-Regular.ttf" },
  { name: "amiriBold", file: "Amiri-Bold.ttf" },
  { name: "cairoRegular", file: "Cairo-Regular.ttf" },
  { name: "cairoBold", file: "Cairo-Bold.ttf" }
]

try {
  const fontsData = {}

  fonts.forEach(({ name, file }) => {
    const fontPath = path.join(__dirname, "../static/fonts", file)

    console.log(`🔍 Looking for ${name} at:`, fontPath)

    if (!fs.existsSync(fontPath)) {
      console.log(`⚠️  ${file} not found, skipping...`)
      return
    }

    const fontData = fs.readFileSync(fontPath)
    const base64Font = fontData.toString("base64")

    fontsData[name] = base64Font

    console.log(`✅ ${name} converted!`)
    console.log(`   📊 Size: ${(base64Font.length / 1024).toFixed(2)} KB`)
  })

  const utilsDir = path.join(__dirname, "../utils")
  if (!fs.existsSync(utilsDir)) {
    fs.mkdirSync(utilsDir, { recursive: true })
  }

  const outputPath = path.join(utilsDir, "fonts.js")
  const fileContent = `// Fonts - Auto-generated on ${new Date().toISOString()}
// Do not edit this file manually

// Amiri Fonts
export const amiriRegularBase64 = "${fontsData["amiriRegular"] || ""}"
export const amiriBoldBase64 = "${fontsData["amiriBold"] || ""}"

// Cairo Fonts
export const cairoRegularBase64 = "${fontsData["cairoRegular"] || ""}"
export const cairoBoldBase64 = "${fontsData["cairoBold"] || ""}"
`

  fs.writeFileSync(outputPath, fileContent)

  console.log("\n✅ All fonts converted successfully!")
  console.log("📁 Output:", outputPath)
} catch (error) {
  console.error("❌ Error:", error.message)
  process.exit(1)
}
